name = "SDFT"
uuid = "cf42e0f7-6d48-47b6-bdd6-b7610c6d69a1"
authors = ["xuequan818 <xuequan818@gmail.com>"]
version = "1.0.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
DFTK = "acf6eb54-70d9-11e9-0013-234b7a5f5337"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ExtXYZ = "352459e4-ddd7-4360-8937-99dcb397b478"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Peaks = "18e31ff7-3703-566c-8e60-38913d67486b"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PseudoPotentialData = "5751a51d-ac76-4487-a056-413ecf6fbe19"

[compat]
DFTK = "0.7.16"
Distributions = "0.25.120"
ExtXYZ = "0.2.2"
Peaks = "0.6.0"
PseudoPotentialData = "0.2.4"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
